name: Run Ruff Lint

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ruff
      - name: Grant execute permission for lint-check.sh
        run: chmod +x ./lint-check.sh
      - name: Lint with Ruff
        run: ./lint-check.sh